before_install:
  # Create .netrc for private repo install
  - 'echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc'
# Branch whitelist
branches:
  only:
    - master
language: node_js
node_js:
  - '6'
cache:
  directories: null
  # - bower_components # disabled, due to an increase in delayed breakages

addons:
  sauce_connect: true
after_success:
  - 'codeclimate-test-reporter < coverage/lcov.info'
